theme: just-the-docs
#logo: 'assets/images/longo-logo.png'
title: 'zezeze'

url: https://longo-lab.github.io

# Color scheme (_sass/color_schemes)
color_scheme: stanford

# Aux links
aux_links:
  'zezeze':
    - 'https://med.stanford.edu/longo-lab.html'
aux_links_new_tab: true

# Callouts
callouts:
  info:
    title: Metadata
    color: stanford-green
    opacity: 0.05
  note:
    color: stanford-red
    opacity: 0.05

# For copy button on code
enable_copy_code_button: true