theme: just-the-docs
#logo: 'assets/images/longo-logo.png'
title: 'Zetian Jia doc'

url: https://zetian-jia.github.io/EpigeneX/

# Color scheme (_sass/color_schemes)
color_scheme: stanford

# Aux links
aux_links:
  'github.io':
    - 'https://zetian-jia.github.io/EpigeneX/'
aux_links_new_tab: true

# Callouts
callouts:
  info:
    title: Metadata
    color: stanford-green
    opacity: 0.05
  note:
    color: stanford-red
    opacity: 0.05

# For copy button on code
enable_copy_code_button: true

# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # 聚焦到搜索输入框 `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true